name: mediovales
favicon: null
layout_spectrum: 0.13719333498738706
typography_spectrum: 0.7038441153708845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.375
  lightness: 0.3893506017047912
  saturation: 0.9448295857291669
  rhythmicContrast: 0.2877714619971812
purpose: []
