name: mediovales
favicon: null
layout_spectrum: 1
typography_spectrum: 0.93745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#badcff'
    - '#576d78'
    - '#101415'
    - '#fdfeff'
    - '#939f60'
  brandStrength: 0.5
  lightness: 0.3893506017047912
  saturation: 0.75
  rhythmicContrast: 0.2877714619971812
purpose: []
